### ISSUE TITLE
VS Code: Create New Project instructions lacking

### ISSUE THREAD

**Issue by gillenhaalb** [MicrosoftDocs/quantum-docs-pr#610]
Both the instructions [here](https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview#develop-with-c-using-visual-studio-code) and [here](https://docs.microsoft.com/en-us/quantum/how-to-guides/create-qsharp-project?view=qsharp-preview#create-a-c-project-using-vs-code) seem to gloss over a few important steps. 
(2) below is a simple addition to the docs which I will PR, but (1) could really use some input regarding how we should go about the fix. I do note a workaround that could be added to the docs.

This is with .NET Core SDK 3.0 and freshly installed/updated VS Code (1.39.2) and QDK extension (0.10.19103107).

1. It suggests that upon **Debug** -> **Start Without Debugging** the project will run immediately, which seems to be very much not the case. I get hit with the decision between
    - .NET Core
    - launch.json
    
    both of which send me down a rabbit hole of errors. I recall an old version of these docs had a brief (but still inadequate) mention of this step saying that launch.json "should" work. 
It became a confusing mess quickly, but was entirely avoided by simply opening a terminal *in* VS Code and running the project with `dotnet run`.

2. After **Command Palette** -> **Q#: Create New Project** there is a decision to be made between 
    - Standalone console application
    - Quantum library
    - Unit testing

    which I'd imagine could be important, but isn't mentioned at all. 
It appears "standalone console application" is the one we want them to click, because Quantum library doesn't create a C# host file

**Comment by gillenhaalb** [comment]
Unsure if it's relevant, as everything still worked immediately when using `dotnet run`, but a heads up in case it's pertinent:
- upon creating and opening the new project, a popup appears that some errors occured. Viewing leads to the Output window for "OmniSharp Log" with the following:

Starting OmniSharp server at 11/5/2019, 3:18:27 PM
    Target: c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial

OmniSharp server started.
    Path: C:\Users\Gillenhaalb\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\OmniSharp.exe
    PID: 15776

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.3.29424.173 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.0 - "C:\Users\Gillenhaalb\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.3.29424.173 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial\QFTtutorial.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial\QFTtutorial.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial' on host 11892.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial\QFTtutorial.csproj'.
c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial\QFTtutorial.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial\QFTtutorial.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 129
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 72
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 98
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 308

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\Gillenhaalb\VSCode_qsharp\QFTtutorial\QFTtutorial.csproj

**Comment by gillenhaalb** [comment]
Fixed with updates to install page
