### ISSUE TITLE
Error : dotnet iqsharp install

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/quantum-docs-pr#617]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/quantum-docs-pr.ko-KR/issues/1

@k19812 commented 18 hours ago — with docs.microsoft.com
My Windows10 account folder name includes a 'White Space'. (ex : 'Acc A')
So I can't install and I get an error.
Renaming a Windows10 account forder name is too complicated and risky.
(C:\Users\Acc A -&gt; C:\Users\AccA)
Is there any way to fix the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Learn how to install the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview#feedback)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment]
Hi @k19812,

Can you please paste in the error you see.

Thank you!

**Comment by k19812** [comment]
Hi @natke 

* Problem : 
- My Windows10 account folder name is 'C:\\Users\\Sirius B'.
- But when I install it (dotnet iqsharp install), it doesn't recognize 'C:\\Users\\Sirius B', but it tries to recognize 'C:\\Users\\Sirius' Perhaps spacing is a problem.


* Error message :

C:\Windows\system32>dotnet iqsharp install
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\Scripts\jupyter-kernelspec.EXE\__main__.py", line 9, in <module>
  File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\jupyter_client\kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\jupyter_client\kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\jupyter_client\kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\shutil.py", line 318, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Sirius'

C:\Windows\system32>


Thank you

**Comment by natke** [comment]
Thank you @k19812,

I have reproduced the error when the user's home directory has a spaces in it.

I will raise an issue in the product repo, but in the mean time you can workaround this issue by installing the QDK in a user account that has no spaces.

**Comment by k19812** [comment]
Yes I know.
It's a big risk to rename my account folder.
Because there are already many development environments.
I hope to be able to install even if there are spaces.

I want to develop in 'python' on 'VS Code'. (Q# + Python + Deep Learning)
But now I am developing with 'C#' on 'Visual Studio 2019'. (Q# + C#)
I Love Q#
Thank you!
